import type { ReportOutboundFilterDTO } from "../../../../@types/DTOs/ReportOutboundFilterDTO";
import { PAGINATION_FILTER } from "../../../../constants/PAGINATION";

export const EMPTY_FORM: ReportOutboundFilterDTO = {
  pullOutDateFrom: null,
  pullOutDateTo: null,
  actualCheckInDate: null,
  icrReferenceNumber: null,
  principalId: null,
  productCategoryId: null,
  goodsReceiptId: null,
  pickListDetailsId: null,
  goodIssueId: null,
  ocrNumber: null,
  id: null,
  name: null,
  description: null,
  skuCode: null,
  proNumber: null,
  deliveryNote: null,
  unitOfMeasurementId: null,
  batchNo: null,
  expirationDate: null,
  palleteCount: null,
  quantity: null,
  lengthCm: null,
  heightCm: null,
  widthCm: null,
  cubicMeter: null,
  customerName: null,
  shelfDetailsId: null,
  totalAmount: null,
  bookingDetailsId: null,
  isStaging: false,
  ...PAGINATION_FILTER,
};
