import type { InboundFilterDTO } from "../../../../@types/DTOs/InboundFilterDTO";

export const EMPTY_FORM: InboundFilterDTO = {
  actualCheckInDate: null,
  icrReferenceNumber: null,
  principalId: null,
  productCategoryId: null,
  goodsReceiptId: null,
  id: null,
  name: null,
  description: null,
  skuCode: null,
  proNumber: null,
  deliveryNote: null,
  unitOfMeasurementId: null,
  batchNo: null,
  expirationDate: null,
  palleteCount: null,
  quantity: null,
  lengthCm: null,
  heightCm: null,
  widthCm: null,
  cubicMeter: null,
  customerName: null,
  shelfDetailsId: null,
  totalAmount: null,
  bookingDetailsId: null,
};
