import type { ReportPickListFilterDTO } from "../../../../@types/DTOs/ReportPickListFilterDTO";

export const EMPTY_FILTER: ReportPickListFilterDTO = {
  actualCheckInDateFrom: null,
  actualCheckInDateTo: null,
  icrReferenceNumber: null,
  principalId: null,
  productCategoryId: null,
  goodsReceiptId: null,
  allowZeroBalance: false,
  allowNullGoodIssue: true,
  id: null,
  name: null,
  description: null,
  skuCode: null,
  proNumber: null,
  deliveryNote: null,
  unitOfMeasurementId: null,
  batchNo: null,
  expirationDate: null,
  palleteCount: null,
  quantity: null,
  lengthCm: null,
  heightCm: null,
  widthCm: null,
  cubicMeter: null,
  customerName: null,
  shelfDetailsId: null,
  totalAmount: null,
  bookingDetailsId: null,
  pageSize: 10,
  currentPage: 1,
};
